apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-apitoken-acl
type: Opaque
data:
  apitoken.aclpolicy: |
    description: API project level access control
    context:
      project: '.*' # all projects
    for:
      resource:
        - equals:
            kind: job
          allow: [create,delete] # allow create and delete jobs
        - equals:
            kind: node
          allow: [read,create,update,refresh] # allow refresh node sources
        - equals:
            kind: event
          allow: [read,create] # allow read/create events
      adhoc:
        - allow: [read,run,kill] # allow running/killing adhoc jobs and read output
      job:
        - allow: [create,read,update,delete,run,kill] # allow create/read/write/delete/run/kill of all jobs
      node:
        - allow: [read,run] # allow read/run for all nodes
    by:
      group: api_token_group

    ---

    description: API Application level access control
    context:
      application: 'rundeck'
    for:
      resource:
        - allow: '*' # allow create of projects
      project:
        - allow: '*' # allow view/admin of all projects
      project_acl:
        - allow: '*' # allow admin of all project-level ACL policies
      storage:
        - allow: '*' # allow read/create/update/delete for all /keys/* storage content
    by:
      group: api_token_group